{% set setup = load_setup_py_data() %}

package:
  name: pyoctomap
  version: {{ setup.get('version') }}

source:
  git_url: https://github.com/lespim/pyoctomap.git
  git_rev: v{{ setup.get('version') }}

build:
  number: 0
  script: bash conda/recipe/build.sh

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config        # [unix]
    - make              # [unix]
  host:
    - python
    - pip
    - cython >=0.29
    - numpy
    - setuptools >=61
    - wheel
    - eigen             # [unix]
  run:
    - python
    - numpy

test:
  imports:
    - pyoctomap
  commands:
    - python -c "import pyoctomap as m; print('version', getattr(m, '__version__', 'unknown')); t = m.OcTree(0.1); t.updateNode([1.0, 2.0, 3.0], True); n = t.search([1.0, 2.0, 3.0]); assert n is not None and t.isNodeOccupied(n); print('sanity ok')"

about:
  home: https://github.com/lespim/pyoctomap
  summary: Python binding of the OctoMap library with bundled shared libraries.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lespim
